### ISSUE TITLE
Windows build setup instructions

### ISSUE THREAD

**Issue by SQLServerIO** [skiselev/8088_bios#13]
### Building BIOS'es For Fun and Profit

This isn't too difficult just follow the instructions.

**Download and installs**
NASM - the latest stable version works
[NASM](https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-installer-x64.exe)

GNUWin32 tools (includes make and tr)
[GNUWin32](https://sourceforge.net/projects/getgnuwin32/files/getgnuwin32/0.6.30/GetGnuWin32-0.6.3.exe/download)

rawwrite dd for windows version 0.6beta3
We need this since it implements /dev/zero internally
[rawwrite dd](http://www.chrysocome.net/downloads/dd-0.6beta3.zip)

**rawwrite dd instructions**
rename GNUWin32\bin\dd.exe to dd_gnu.exe
dd we downloaded and unzipped should be put in the GNUWin32\bin folder

**Modify your Windows path**
Add NASM and GNUWin32 to the windows path under settings->advanced settings->Environment Variables->Path(ether local or system)
NASM defaults to c:\program files\NASM
GNUWin32 defaults to c:\program files (86)\GnuWin32\bin
_Just changing your path at the command prompt will not work!_

Create batch file bios_lst.bat in the same folder as your source files
place this in the file and save.
```@echo off dir *.inc /B > bios.lst ```

(needed for building with NASM)

**MakeFile Changes**
Modify the MakeFile
replace ibs=1k to just bs=1k 
the version of dd we downloaded doesn't support ibs but it won't effect the build or the bin file

**Running The Build**
Run start a administrator command console
switch to your source directory
run the bios_lst.bat file
run make in the source folder
take the output and enjoy!

**Burning the BIOS**
There is no minipro alternative for windows other than the gui so if you have a minipro stick to what you know.

**First startup**
Your first startup will be slow
it will eventually complain about missing or corrupted nvram settings
go into the settings menu and clean it up.

### Next Steps
Go learn assembly

**Comment by skiselev** [comment]
Thanks for taking your time and writing this instruction!

I published the instruction [here](https://github.com/skiselev/8088_bios/blob/master/Building_Instructions-Windows.md) with some changes:

1. Use separate GNUWin32 make and CoreUtils packages. The entire GNUWin32 is not needed.
2. Path can be set in the current CMD session. It just will not be persistent - will go away once the CMD session is closed
2. bios_lst.bat is not needed, bios.lst is an output file generated by NASM
3. No need to run make as an Administrator

**Comment by spark2k06** [comment]
In Windows, the fastest and easiest thing from my point of view is to use WSL and follow the instructions like Linux, it is another additional option, and it is the one that I use  :-)
