### ISSUE TITLE
No BIOS Screen on monochrome VGA Monitor

### ISSUE THREAD

**Issue by explit7** [skiselev/8088_bios#24]
Dear @skiselev, dear @spark2k06, dear @horkthane 

Found a weird bug on an old monochrome VGA Monitor EIZO 4050:
The whole BIOS Screen of the Micro8088 BIOS is not displayed.
I see the Trident TVGA9000i BIOS Message, afterwards i see black screen with moving cursor and after some time i see XTCF BIOS messages:
 
On a normal VGA Display anything is working fine.
Could it be a problem with the Trident TVGA9000i VGA Card or Micro8088 BIOS issue?

https://user-images.githubusercontent.com/11852348/207559719-65436910-8631-43e7-9052-62126ce7c1ff.mp4

Update 1:
Seen this pull request by @horkthane 
https://github.com/skiselev/8088_bios/compare/master...horkthane:8088_bios:master

I think its exact my Problem.

Update 2:
Build the 0.9.8 BIOS with @horkthane patch. 

Now - BIOS is shown fine on the monochrome VGA Monitor, but recognized as MDA or Hercules during BIOS messages.
It would be great, when it would be recognized as VGA but would also work on monochrome VGA displays.
Thanks!

**Comment by skiselev** [comment]
You are  right on track.
If I recall correctly it has to do with the equipment bits not set up correctly.
I need to find time to test the patch and figure out how to distinguish between monochrome VGA and MDA/Hercules. But that's just a cosmetic issue, it shouldn't impact the operation of the system

**Comment by horkthane** [comment]
Taking a wild stab at EGA/VGA detection without using the equipment bits, and maybe checking 40:A8 would work?  Supposed to be the BIOS Video Save/Override Pointer Table address?  Probably only something other than 0 when a VGA bios sets it to something during it's initialization.  I'd test to make sure, but I only have VGA cards.

**Comment by explit7** [comment]
I have tested this patch from @horkthane 
https://github.com/skiselev/8088_bios/commit/1dc3c95cfadf61811a3afaa642be0e78bc550e56

Now it works like it should.
Monochrome VGA works, bios shows EGA/VGA as a Display and text is shown up correctly.

**Comment by horkthane** [comment]
Brave man.  I think I mentioned in that commit that I hadn't even tested it.  Although I suppose we still don't know if it correctly detects non EGA/VGA cards with those changes.

**Comment by skiselev** [comment]
Should be fixed in the latest master... at least it works well for me :)
