### ISSUE TITLE
Crash on floppy write with PC-DOS 3.30

### ISSUE THREAD

**Issue by TzOk83** [skiselev/8088_bios#25]
I've encountered a 100% repetitive crash when trying to write anything to floppy disk when booting to PC-DOS 3.30. When I try to format a floppy, it goes to 100% and crashes at the end (creating file system). The computer I use is Micro 8088. When I use GLaBIOS with your Multi-Floppy BIOS Extension v2.6, it works normally. Also, under PC-DOS 5.00 it works fine with your BIOS, as well as with any other BIOS.

**Comment by skiselev** [comment]
Thank you for this bug report. I'll try to find time to reproduce it on my end

**Comment by TzOk83** [comment]
I was running a V20 CPU on Micro 8088 board with your BIOS, and no other extensions. I was using PC-DOS 3.30 and a GOTEK floppy emulator. I will try to repeat the experiment. But I've already tried 2 different DOS 3.30 boot disk images.

**Comment by skiselev** [comment]
I've used [this one](https://winworldpc.com/download/c2a327c3-97c3-89c2-b4c2-8f11c3a4c2ac).
I am using a real 3.5" / 1.44MB floppy drive. The DOS image itself is 720KB diskette, while all diskettes I have are 1.44 MB. So I covered the "density detect" hole on the disk with a piece of tape, and reformatted it as 720 KB. I created the bootable disk from the image on the Micro 8088 itself using the [rawrite](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/rawrite.html) utility

**Comment by TzOk83** [comment]
Ok, so I will test with real floppy, as now, I have XT-CF, so I will be able to make a disk.
One of the Images I've tried is the same you have linked.

![dos-330](https://user-images.githubusercontent.com/34161432/214375626-0329e787-086c-40b7-9663-c71f62af1279.jpg)

**Comment by skiselev** [comment]
I ported my Multi-floppy BIOS code back to 8088 BIOS. It fixes some re-read errors mentioned here https://github.com/skiselev/8088_bios/issues/17. Please give it a try.

**Comment by TzOk83** [comment]
I may confirm, that problem with writing to floppy in PC-DOS 3.30 is now fixed.
