### ISSUE TITLE
Makefile needs small update

### ISSUE THREAD

**Issue by maxgvz** [skiselev/8088_bios#26]
On the FreeBSD with locale UTF-8, I've encountered with 'tr' utility problem. In fact I could made it work only with using `LANG=C` patch. Like this:

```
bios-micro8088.bin: bios.bin
	dd if=/dev/zero ibs=1k count=40 | LANG=C tr "\000" "\377" > bios-micro8088.bin
	cat bios.bin >> bios-micro8088.bin
	dd if=/dev/zero ibs=1k count=64 | LANG=C tr "\000" "\377" >> bios-micro8088.bin
...
```

Would be helpful to apply this patch to all commands with 'tr'. This patch works okay on linux OS as well.

**Comment by skiselev** [comment]
Fixed in master branch. Thank you for your contribution!
