### ISSUE TITLE
Book 8088 BIOS in context of ELKS

### ISSUE THREAD

**Issue by Vutshi** [skiselev/8088_bios#39]
Dear Sergey,

I am trying to boot ELKS on Book 8088. I didn’t yet flash your BIOS so the laptop is on stock version. I wonder whether you have any recommendations on the correct CHS configuration of the boot drive (cf card)?

I have also created a corresponding issue in the ELKS repository https://github.com/jbruchon/elks/issues/1619

Thank you.

**Comment by skiselev** [comment]
It might be related to XT-IDE BIOS.
Stock Book8088 has an outdated XT-IDE BIOS extension, so I'd start with trying newer XT-IDE BIOS. My Book8088 BIOS image includes the latest (to date) version

**Comment by Vutshi** [comment]
Thank you @skiselev. Then I’ll wait for new flash chips to arrive and I’ll use your Book8088 image to play with ELKS.

**Comment by skiselev** [comment]
@Vutshi where you able to re-test ELKS with the new XT-IDE / 8088 BIOS?

**Comment by Vutshi** [comment]
Hi @skiselev,
Yes, my book8088 currently works using your BIOS (end of June version). I had some troubles first with defect CF cards, then my newly ordered Transcend card appeared to be incompatible with XT-ide and MINIX ELKS. Finally, one more CF card get it all working well.

**Comment by skiselev** [comment]
Thanks for testing!
It sounds like the problem was due to CF card incompatibility.
