### ISSUE TITLE
AT KBC - check other input bit for video mode select?

### ISSUE THREAD

**Issue by SanguineBrah** [skiselev/8088_bios#41]
Even though the Xi 8088 does not have a trace running to it, would it be possible to also check input port 17 (pin 34) on the 8242 for the other video mode bit in order to make it possible to solder a switch that would enable 40-column CGA mode on this board?

**Comment by skiselev** [comment]
It should be possible, at least looking at VT82C42N keyboard datasheet. It wasn't a standard feature in IBM AT though, and I am not positive that other keyboard controller will support it.
On the BIOS side, it would require modifications to this subroutine:
https://github.com/skiselev/8088_bios/blob/3ca115140ac6d55d5f1d5a5031b89cb2bcfb74ed/src/at_kbc.inc#L468

**Comment by SanguineBrah** [comment]
Ah yeah, looking at the datasheet for the HT6542B I can see that it uses that pin for keyboard inhibit. Perhaps pin 32 (bit 5) is more appropriate, as it seems to be indicated as general purpose I/O across VT82C42N, 8242 and HT6542B as far as I can tell.

**Comment by SanguineBrah** [comment]
Closing issue
