### ISSUE TITLE
Create 1.0.0 release?

### ISSUE THREAD

**Issue by ConiKost** [skiselev/8088_bios#43]
Hi! Since you added support for Book 8088 and misc stuff, could you create the release 1.0.0?
Changelog indicate this version, but no release on Github?

**Comment by skiselev** [comment]
Eventually, once we do enough testing :)

**Comment by skiselev** [comment]
1.0.0 release has been published.
Enjoy!

**Comment by ConiKost** [comment]
Hooray :-)
