### ISSUE TITLE
XT IDE Turbo Basic compatibility

### ISSUE THREAD

**Issue by jinshin** [skiselev/8088_bios#45]
Hi.
Turbo Basic hangs on file load on Book8088.
Fix is described here:
https://www.vogons.org/viewtopic.php?t=75536
I've tested it and it works.
Built and tested BIOS ( tbh, tested only v20, i afraid my winbond chip will soon break :) ) here : https://github.com/jinshin/Book8088

It's not a bug in BIOS, but since XT IDE BIOS is included in your binary and if there's no objections using XT IDE BIOS in full operating mode, you might consider changing that option for XT IDE BIOS in binary release.

Best,
Serhii

**Comment by skiselev** [comment]
Apologies for a delay. I reconfigured the XT-IDE to work in full operating mode, and rebuilt the binary/ROM images
Please test
https://github.com/skiselev/8088_bios/commit/63b0b7f8a812dc2b4671aed261051b59c762e064
