### ISSUE TITLE
FreeDOS Fails to Boot in Book 8088

### ISSUE THREAD

**Issue by oblende** [skiselev/8088_bios#46]
FreeDOS fails to boot with the new bios in the Book 8088. This is a regression compared to the BIOS that came in the computer.
CF card brand used is Fujifilm 128MB.  This might also be a FreeDOS problem to as an installation on the original 512 MB card will fail with the message of Starting FreeDOS then an unending beep in both the original BIOS that came with the computer and your BIOS.

**Comment by oblende** [comment]
I am an idiot. It looks like the BIOS is expecting to see the card in CHS geometry instead of LBA. I think for the Book 8088 that booting media in LBA would be a good feature request. I solved my problem by using dd to copy the CF card that came with the Book 8088 onto a 4 GB CF card. I then in a VM installed FreeDOS onto it.

**Comment by roytam1** [comment]
there is another discussion in http://www.bttr-software.de/forum/board_entry.php?id=21061 shows that FreeDOS has to disable its LBA support in order to boot in Book8088. and it seems that either XT-IDE BIOS and/or Xi8088 BIOS go off the track when FreeDOS kernel calls Int 13h,AH=41h twice.
