### ISSUE TITLE
[book8088] BIOS detects floppy drive when there isn't one connected

### ISSUE THREAD

**Issue by ImanolBarba** [skiselev/8088_bios#49]
By default, the V20 optimised book8088 BIOS (I haven't tried the other one), reports a floppy drive connected when there isn't one in the machine

**Comment by skiselev** [comment]
BIOS does not detect floppy drives. Unfortunately Book8088 does not provide a configuration storage mechanism such as jumpers or NVRAM. So one floppy drive is "hard coded". 
If for whatever reason you don't like the fact that BIOS has one floppy configured while there none, it is possible to edit the BIOS code and rebuild it.
See default_floppy in setup.inc

**Comment by ImanolBarba** [comment]
Yeah I figured after looking at the code (should've done that before opening the issue sorry)

Two questions:
- I plan on installing the monster FDC card on this machine, I assume this will be fine and the floppy BIOS will override these settings?
- Is there a possibility to detect the floppy type (or at the very least its presence) in a way that is portable?
