### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by Yrouel** [skiselev/8088_bios#57]
I wrote the instructions to build this on macOS using Homebrew as the basis to install everything else that's necessary.

I didn't just make a pull request because while building the project works per se there is some quirkiness in the tr utility included in macOS (Sonoma in my case but I suspect it applies to other versions as well) in that LANG=C is seemingly ignored and the result is that the output of for example `dd if=/dev/zero ibs=1k count=40 | LANG=C tr "\000" "\377"` is 0xC3BF instead of 0xFF which produces invalid binaries.
Using LC_ALL=C instead fixes the problem.

So if LC_ALL=C is also applicable to Linux without breaking anything consider using that instead to make the build process compatible with macOS without a special case for it

[Build_Instructions-macOS.md](https://github.com/skiselev/8088_bios/files/13468407/Build_Instructions-macOS.md)
[CMakeLists.txt](https://github.com/skiselev/8088_bios/files/13468408/CMakeLists.txt)

**Comment by skiselev** [comment]
Thanks for the LC_ALL=C suggestion!
I'll test it on Linux and if that works, I'll modify the CMakeLists.txt

**Comment by skiselev** [comment]
Fixed in https://github.com/skiselev/8088_bios/commit/a03b60b6cef69a64ec2384f07534d3943a0d3775
