### ISSUE TITLE
Check for STI in io_wait_latch

### ISSUE THREAD

**Issue by skiselev** [skiselev/8088_bios#58]
io_wait_latch in delay.inc disables interrupts but doesn't enable them back

Reported by batus74@meta.ua

**Comment by 640-KB** [comment]
Are you certain about this? The `pushf` saves the caller's interrupt flag state, disables interrupts while reading the latched bytes and then restores `IF` to the previous state with `popf`. So if interrupts were off previously, it will return with them off and if they were on, it will return with them on again.

https://github.com/skiselev/8088_bios/blob/a03b60b6cef69a64ec2384f07534d3943a0d3775/src/delay.inc#L105-L115

Is this causing issues with something?

**Comment by skiselev** [comment]
@640-KB thank you for checking on this!
Doesn't seem to be a bug, POPF will restore the flags at the end of the routine
