### ISSUE TITLE
Time and DSE issues in version 0.9.7

### ISSUE THREAD

**Issue by spark2k06** [skiselev/8088_bios#6]
Some issues detected in version 0.9.7:

1. When the time is modified from the setup, it does not seem to apply immediately. A time command in msdos shows the previous time. Only updated after a machine restart (CTRL + ALT + DEL)

2. The msdos time command always disables the DSE, and it is due to this code in time1.inc:

```
and	dl,cmos_dse		; mask the daylight saving flag
and	ah,~cmos_dse		; clear daylight saving flag for now
or	ah,dl			; add it from the input
mov	al,cmos_control_b
call	rtc_write		; write control B register
```

**Comment by skiselev** [comment]
1. Weird. The BIOS setup utility updates the time and the date immediately in RTC using INT 1Ah/AH=03h and INT 1Ah/AH=05h functions. I'll test it on my system.
2. It must be a bug in MS-DOS then... INT 1Ah/AH=03h sets DSE flag to the value specified in DL. The piece of code that you copied does exactly that. If DOS passes DL=0, the BIOS will disable DSE

**Comment by spark2k06** [comment]
1. If you want I prepare and show a video :-)

2. How does MS / DOS know the DSE value that must be passed to the DL register with the function 1Ah / AH = 03h? It seems as if it always set 00h en DL

**Comment by spark2k06** [comment]
1. When time is update from setup, the system timer (INT 1Ah/AH=03h) were not updated. I have fixed it this way, you can check it: https://github.com/spark2k06/8088_bios/commit/4324d606059c4e45a384a4b24dec9eef11d6940b

**Comment by spark2k06** [comment]
2. Here you can see how the service 21h - 2Dh sets the DSE value of the RTC always at 0:

https://youtu.be/DHZTjWwerUQ

**Comment by spark2k06** [comment]
I have created a pull request on the last changes of this issue, including the fact of deactivating DSE, as we have discussed by email.

**Comment by spark2k06** [comment]
Last modification checked:

https://github.com/skiselev/8088_bios/commit/ec830ea677c56d78a6a47979a4cd59b79a1f59fc

For my part, if you have no other changes in mind, you could already add a new version of the BIOS to the corresponding folder of your Micro8088 repository:

https://github.com/skiselev/micro_8088/tree/master/BIOS
