### ISSUE TITLE
Doubt: XT-IDE Bios vs. XT-IDE card

### ISSUE THREAD

**Issue by giobbino** [skiselev/8088_bios#61]
Hi, just a silly doubt, actually...

I'm waiting for PCB and parts for the Micro8088 and I was planning the further steps. 

I've seen that there are two BIOS versions I would use:

bios-micro8088-noide.rom  -- BIOS image for Micro 8088 Version 1.1
bios-micro8088-xtide.rom   -- BIOS image for Micro 8088 Version 1.1 with XT-IDE

I'm going to use an XT-IDE card, so I suppose I should use the "bios-micro8088-xtide.rom" file. BUT: does it replace the actual XT-IDE on-board Bios? Or it is just a matter of compatibility/optimization?

---> If it replaces the XT-IDE actual Bios, should I forget the XT-IDE "xtidecfg.com" BIOS configuration step?

-------------------------
ONE MORE QUESTION: I've seen in the Micro8088 there's a 0.9 release; should I use the 1.1 or the 0.9 ?

thank you!

**Comment by explit7** [comment]
Hi. Personally i use normal micro8088 rom file, without xtide rom. I use the XTIDE ROM of my XTIDE Card. The Micro8088 ROM which include XTIDE ROM is for system, which alredy have CF Slot or ide controller, like NuXT or Book8088 etc.
Micro 8088 BIOS 1.0 is the actual one.

**Comment by giobbino** [comment]
Thank you, it's all clear to me now :-)

**Comment by TzOk83** [comment]
You can have XT-IDE BIOS in either a system ROM or a controller ROM it doesn't matter, yet you should have it on only one of them. In my Micro8088 I have a Monotech XT-CF-Mini card with its own ROM, and I have XT-IDE BIOS in the controller ROM, and the "noide" system BIOS.

**Comment by skiselev** [comment]
I don't think I ever published version 1.1. The latest official version is 1.0.0.

The difference between XT-IDE version, is that it has the XT-IDE image in it. That allows you to save the EPROM/EEPROM on your XT-IDE or XT-CF-Lite card. It also makes the memory typically used for the extension BIOS ROM on these cards available for other uses, e.g. UMBs.

The XT-IDE image included is configured in XT-CF-LITE mode, port 0x300 (if I recall correctly). In case you want to reconfigure it with XTIDECFG.COM, the best course of action would be downloading the XUB BIOS extension, configuring it the way you want it, and then making your own BIOS image, by combining configured XUB BIOS and 8088 system BIOS.

**Comment by giobbino** [comment]
I mentioned the 1.1 release because the BIOS releases table (see: https://github.com/skiselev/8088_bios/tree/master#bios-images) says:

bios-micro8088.bin | BIOS image for Micro 8088 **Version 1.1** to use with xiflash utility
bios-micro8088-noide.rom | BIOS image for Micro 8088 **Version 1.1**
bios-micro8088-xtide.rom | BIOS image for Micro 8088 **Version 1.1** with XT-IDE

but, hey, no problem at all :-)
--------------------------------
At first, I think I will use the no-ide version, and then use the xt-ide bios on the xt-ide card. It seems to me the straightest way to begin..

thank you all for the explanations! :-)
