### ISSUE TITLE
Multitasking MS-DOS 4.0: Non-System disk error

### ISSUE THREAD

**Issue by Vutshi** [skiselev/8088_bios#72]
It seems the BIOS does not recognize MS-DOS-4.0M as bootable. This affects the Book8088 and the MartyPC emulator:
![MartyPC_skiselev](https://github.com/skiselev/8088_bios/assets/4971779/1c7e763c-bbe8-419b-96ff-477da800d9d1)

The Multitasking DOS image can be found [here](https://www.pcjs.org/software/pcx86/sys/dos/microsoft/4.0M/).  I have also attached it to this [issue](https://github.com/dbalsom/martypc/issues/120) in MartyPC, where it revealed a bug in another BIOS.

**Comment by skiselev** [comment]
This error message is not coming from the BIOS. It is typically printed by the boot sector code, when it cannot read the disk or find DOS files (IO.SYS, and MSDOS.SYS) as the first two entries in the root directory of the boot device. For example, see this [MS-DOS 5 boot sector analysis](https://thestarman.pcministry.com/asm/mbr/DOS50FDB.htm).

I see that your BIOS is configured with 1.44 MB floppies, while it appears that 4.00M disks are 360 KB disks. Potentially this can be the source of the issue (or not, but worth checking).

Also, I can't seem to find the DOS image at the link provided above. I found this: https://github.com/jeffpar/pcjs-diskettes/tree/master/pcx86/sys/dos/microsoft/4.0M, but it is in JSON format, and I don't know how to convert it to just a binary image. I would appreciate a link to the binary MS-DOS 4.00M images.

**Comment by Vutshi** [comment]
Here is the link to the DOS-4.0M image https://github.com/user-attachments/files/15754189/MSDOS400M-DISK1%2Bgame.img.zip

**Comment by Vutshi** [comment]
> This error message is not coming from the BIOS. It is typically printed by the boot sector code, when it cannot read the disk or find DOS files (IO.SYS, and MSDOS.SYS) as the first two entries in the root directory of the boot device. For example, see this [MS-DOS 5 boot sector analysis](https://thestarman.pcministry.com/asm/mbr/DOS50FDB.htm).

Hmm... With GLaBIOS and the original IBM BIOS I can boot this DOS image in MartyPC.

**Comment by skiselev** [comment]
> Hmm... With GLaBIOS and the original IBM BIOS I can boot this DOS image in MartyPC.

Potentially because neither GLaBIOS nor the original IBM BIOS support 1.44 MB drives. And their floppy disk subsystem is configured to support 360KB disks (160K/180K/320K... maybe 720K disks would work too).

It appears that you're using the XT image of the 8088 BIOS (and Book8088 image). Both are configured to use 1.44 MB diskettes by default. You can modify that. Change the DEFAULT_FLOPPIES setting here https://github.com/skiselev/8088_bios/blob/32f82ebde058d5f92dab9f1da4e5b1906e72c9df/src/config.inc#L120 to something like 11h and recompile the BIOS code.

**Comment by Vutshi** [comment]
> It appears that you're using the XT image of the 8088 BIOS (and Book8088 image). Both are configured to use 1.44 MB diskettes by default. You can modify that. Change the DEFAULT_FLOPPIES setting here
> 
> https://github.com/skiselev/8088_bios/blob/32f82ebde058d5f92dab9f1da4e5b1906e72c9df/src/config.inc#L120
> 
> to something like 11h and recompile the BIOS code.

Thank you, that did the trick for MartyPC. I will take a closer look at my Book8088 later and return if I have questions.
